# Generated by Django 6.0.6 on 2026-06-25 21:39

import apps.consults.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("edited", "Edited"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("note_text", models.TextField(blank=True)),
                ("note_html", models.TextField(blank=True)),
                (
                    "docx_file",
                    models.FileField(
                        blank=True,
                        upload_to=apps.consults.models.consult_docx_upload_to,
                    ),
                ),
                ("source_storage_path", models.CharField(blank=True, max_length=255)),
                ("prompt_system_used", models.TextField(blank=True)),
                ("prompt_user_used", models.TextField(blank=True)),
                ("prompt_edit_used", models.TextField(blank=True)),
                ("format_snapshot_json", models.JSONField(blank=True, default=dict)),
                ("llm_model_key", models.CharField(blank=True, max_length=150)),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "top_p",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("max_tokens", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "presence_penalty",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "frequency_penalty",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("user_instructions", models.TextField(blank=True)),
                (
                    "generation_settings_json",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("last_regeneration_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consult_notes",
                        to="patients.patient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consult_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
