# Generated by Django 6.0.2 on 2026-06-25 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "heading_font_family",
                    models.CharField(default="Arial", max_length=100),
                ),
                ("heading_font_size", models.PositiveSmallIntegerField(default=14)),
                ("heading_bold", models.BooleanField(default=True)),
                (
                    "subheading_font_family",
                    models.CharField(default="Arial", max_length=100),
                ),
                ("subheading_font_size", models.PositiveSmallIntegerField(default=12)),
                ("subheading_bold", models.BooleanField(default=True)),
                ("body_font_family", models.CharField(default="Arial", max_length=100)),
                ("body_font_size", models.PositiveSmallIntegerField(default=11)),
                ("body_bold", models.BooleanField(default=False)),
                ("show_lines_between_sections", models.BooleanField(default=False)),
                ("section_spacing", models.FloatField(default=1.0)),
                ("left_margin", models.FloatField(default=1.0)),
                ("right_margin", models.FloatField(default=1.0)),
                ("top_margin", models.FloatField(default=1.0)),
                ("bottom_margin", models.FloatField(default=1.0)),
                ("header_text", models.CharField(blank=True, max_length=255)),
                ("footer_text", models.CharField(blank=True, max_length=255)),
                ("template_style_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_formats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("user",),
                        name="unique_active_note_format_per_user",
                    )
                ],
            },
        ),
    ]
