# Generated by Django 6.0.6 on 2026-06-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLMModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=100)),
                ("model_key", models.CharField(max_length=150, unique=True)),
                ("display_name", models.CharField(max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                ("supports_temperature", models.BooleanField(default=True)),
                ("supports_top_p", models.BooleanField(default=True)),
                ("supports_max_tokens", models.BooleanField(default=True)),
                ("supports_system_prompt", models.BooleanField(default=True)),
                ("supports_streaming", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "display_name"],
            },
        ),
    ]
