# Generated by Django 6.0.6 on 2026-06-25 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("configdata", "0001_initial"),
        ("consults", "0001_initial"),
        ("formats", "0001_initial"),
        ("patients", "0001_initial"),
        ("prompts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(decimal_places=2, default=0.3, max_digits=4),
                ),
                (
                    "top_p",
                    models.DecimalField(decimal_places=2, default=0.9, max_digits=4),
                ),
                ("max_tokens", models.PositiveIntegerField(default=1800)),
                (
                    "presence_penalty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "frequency_penalty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                ("user_instructions", models.TextField(blank=True)),
                ("settings_snapshot_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "selected_edit_prompt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edit_prompt_sessions",
                        to="prompts.prompt",
                    ),
                ),
                (
                    "selected_format",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_sessions",
                        to="formats.noteformat",
                    ),
                ),
                (
                    "selected_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_sessions",
                        to="configdata.llmmodelconfig",
                    ),
                ),
                (
                    "selected_patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_sessions",
                        to="patients.patient",
                    ),
                ),
                (
                    "selected_system_prompt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_prompt_sessions",
                        to="prompts.prompt",
                    ),
                ),
                (
                    "selected_user_prompt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_prompt_sessions",
                        to="prompts.prompt",
                    ),
                ),
                (
                    "source_consult_note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loaded_sessions",
                        to="consults.consultnote",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
