# Generated by Django 6.0.6 on 2026-06-25 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("synthetic_patient_id", models.CharField(blank=True, max_length=64)),
                ("mrn", models.CharField(max_length=128, unique=True)),
                ("patient_name", models.CharField(max_length=255)),
                ("fake_phn", models.CharField(blank=True, max_length=128)),
                ("province_context", models.CharField(blank=True, max_length=255)),
                ("consult_date", models.DateField(blank=True, null=True)),
                ("consult_type", models.CharField(blank=True, max_length=255)),
                ("referral_source", models.CharField(blank=True, max_length=255)),
                ("reason_for_referral", models.TextField(blank=True)),
                ("age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("sex", models.CharField(blank=True, max_length=64)),
                ("gender_identity", models.CharField(blank=True, max_length=255)),
                ("language", models.CharField(blank=True, max_length=255)),
                ("interpreter_needed", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=255)),
                ("referring_physician", models.CharField(blank=True, max_length=255)),
                (
                    "primary_care_physician",
                    models.CharField(blank=True, max_length=255),
                ),
                ("cancer_site", models.CharField(blank=True, max_length=255)),
                ("tumour_location_detail", models.TextField(blank=True)),
                ("laterality_category", models.CharField(blank=True, max_length=255)),
                ("histology", models.CharField(blank=True, max_length=255)),
                ("grade", models.CharField(blank=True, max_length=255)),
                ("disease_setting", models.CharField(blank=True, max_length=255)),
                ("clinical_stage", models.CharField(blank=True, max_length=255)),
                ("pathologic_stage", models.CharField(blank=True, max_length=255)),
                ("tnm_stage", models.CharField(blank=True, max_length=255)),
                ("metastatic_sites", models.TextField(blank=True)),
                ("disease_burden", models.TextField(blank=True)),
                ("treatment_intent", models.CharField(blank=True, max_length=255)),
                ("presentation_mode", models.TextField(blank=True)),
                ("presenting_symptoms", models.TextField(blank=True)),
                ("symptom_duration", models.CharField(blank=True, max_length=255)),
                ("diagnostic_timeline", models.TextField(blank=True)),
                ("current_symptoms", models.TextField(blank=True)),
                ("weight_loss", models.CharField(blank=True, max_length=255)),
                ("ecog", models.CharField(blank=True, max_length=32)),
                ("past_medical_history", models.TextField(blank=True)),
                ("past_surgical_history", models.TextField(blank=True)),
                ("home_medications", models.TextField(blank=True)),
                ("medication_adherence", models.TextField(blank=True)),
                ("allergies", models.TextField(blank=True)),
                ("living_situation", models.TextField(blank=True)),
                ("occupation_status", models.CharField(blank=True, max_length=255)),
                ("supports", models.TextField(blank=True)),
                ("family_dynamics", models.TextField(blank=True)),
                ("adls_iadls", models.TextField(blank=True)),
                ("mobility_aids", models.TextField(blank=True)),
                ("transportation_barriers", models.TextField(blank=True)),
                ("financial_coverage_issues", models.TextField(blank=True)),
                ("smoking_history", models.TextField(blank=True)),
                ("alcohol_history", models.TextField(blank=True)),
                ("substance_history", models.TextField(blank=True)),
                ("extended_health_benefits", models.TextField(blank=True)),
                ("family_history_cancer", models.TextField(blank=True)),
                ("family_history_autoimmune", models.TextField(blank=True)),
                ("hereditary_risk_flag", models.TextField(blank=True)),
                ("key_labs", models.TextField(blank=True)),
                ("tumour_markers", models.TextField(blank=True)),
                ("imaging_summary", models.TextField(blank=True)),
                ("endoscopy_findings", models.TextField(blank=True)),
                ("pathology_summary", models.TextField(blank=True)),
                ("molecular_summary", models.TextField(blank=True)),
                ("pending_tests", models.TextField(blank=True)),
                ("prior_cancer_treatment", models.TextField(blank=True)),
                ("prior_interventions", models.TextField(blank=True)),
                ("line_of_therapy", models.CharField(blank=True, max_length=255)),
                ("proposed_management", models.TextField(blank=True)),
                ("supportive_care_plan", models.TextField(blank=True)),
                ("referrals", models.TextField(blank=True)),
                ("tumour_board_needed", models.TextField(blank=True)),
                ("follow_up_plan", models.TextField(blank=True)),
                ("provider_style", models.CharField(blank=True, max_length=255)),
                (
                    "note_imperfection_level",
                    models.CharField(blank=True, max_length=255),
                ),
                ("intentional_documentation_gaps", models.TextField(blank=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("seed", "Bundled Seed"),
                            ("manual", "Manual Entry"),
                            ("copy", "Copied Record"),
                            ("import", "Imported"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("source_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["patient_name", "mrn"],
            },
        ),
    ]
